plugins {
    id 'java'
}

group = 'com.network'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':domain')
    implementation project(':repo')
    implementation project(':service')
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}